[package]
name = "crawler"
version = "0.1.0"
authors = ["Konstantin Lopuhin <kostia.lopuhin@gmail.com>"]

[dependencies]
env_logger = "*"
html5ever = "*"
hyper = {git = "https://github.com/hyperium/hyper.git", rev = "6d54a4d"}
log = "*"
mime = "*"
