[package]
name = "rust-broad-crawl"
version = "0.1.0"
authors = ["Konstantin Lopuhin <kostia.lopuhin@gmail.com>"]

[dependencies]
html5ever = "*"
hyper = {git = "https://github.com/hyperium/hyper.git", rev = "6d54a4d"}
mime = "*"
env_logger = "*"
