[package]
name = "rust-broad-crawl"
version = "0.1.0"
authors = ["Konstantin Lopuhin <kostia.lopuhin@gmail.com>"]

[dependencies]
hyper = {git = "https://github.com/hyperium/hyper.git", rev = "220d09f"}
env_logger = "*"
